runtime: python39
entrypoint: sh -c 'python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -b :$PORT billbuddy.wsgi'

env_variables:
    GS_BUCKET_NAME: 'YOUR_GS_BUCKET_NAME'
    GS_PROJECT_ID: 'YOUR_GS_PROJECT_ID'
    DB_NAME: 'YOUR_DB_NAME'
    DB_USER: 'YOUR_DB_USER'
    DB_PASS: 'YOUR_DB_PASS'

beta_settings:
  cloud_sql_instances: billbuddy-428516:asia-east1:my-sql-instance

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /.*
  script: auto
  secure: always
