# Generated by Django 3.2.25 on 2024-07-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240630_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='photo',
        ),
    ]
