# Generated by Django 3.2.25 on 2024-07-03 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_bill_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='members',
            field=models.ManyToManyField(related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
