# Generated by Django 3.2.25 on 2024-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bill_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bank_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='bank_qr_codes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='bank_qr_codes'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
