# Generated by Django 3.2.25 on 2024-07-07 16:18

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240705_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bank_qr_code_upload_to),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_picture_upload_to),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.bank_qr_code_upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_picture_upload_to),
        ),
    ]
