# Generated by Django 3.2.25 on 2024-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240713_0349'),
    ]

    operations = [
        
    ]
