# Generated by Django 5.0.7 on 2024-07-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240713_0402'),
    ]

    operations = [
        
    ]
