# Generated by Django 5.0.7 on 2024-07-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_friend_nickname_note_comment'),
    ]

    operations = [
        
    
    ]
