# Generated by Django 5.0.7 on 2024-07-24 15:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_friend_nickname'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='expense',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.expense_photo_upload_to),
        ),
    ]
