# Generated by Django 3.2.25 on 2024-07-26 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_friend_nickname_expense_photo'),
    ]

    operations = [
        
    ]
