# Generated by Django 3.2.25 on 2024-07-26 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_friend_nickname'),
    ]

    operations = [
        
    ]
