# Generated by Django 3.2.25 on 2024-07-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_friend_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='nickname',
        ),
    ]
