# Generated by Django 3.2.25 on 2024-08-01 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
    ]
