# Generated by Django 3.2.25 on 2024-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='formatted_created_at',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='formatted_created_at',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
